# Generated by Django 4.0 on 2022-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_id', models.CharField(max_length=10)),
                ('my_pw', models.CharField(max_length=12)),
                ('my_titles', models.CharField(max_length=50)),
                ('my_contents', models.TextField()),
                ('my_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
