# Generated by Django 4.0 on 2022-01-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApps', '0002_alter_post_my_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='my_id',
            new_name='my_name',
        ),
    ]
